ARTIFICIAL NEURAL NETWORK STARTING 
STEPS
1. LIB
2. DATASET
3. PREPROCESSING
4. SPLITTING
5. FEATURE SCALING
5. MAKING ANN
6. COMPILING IT
7. EVALUATING IT

churn modeling :- here we have teh record of a bank customers we have to predict wether they will leave the bank or not

import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

importing the dataset

In [2]:
data=pd.read_csv('../datasets/Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
data.isnull().sum()  #no null values

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Splitting into x and y 
1. in x first three columns are not important
2. row no,customer id and surname

In [4]:
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

Preprocessing of this data

1. Label Encoder for gender

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])  #index of gender or column =2
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

1. 0---> Female
2. 1--->Male

2. One Hot Encoder for the categories of the countries

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))     #here already 1 is given as argument which is the index of the countries
#now extra three columns will be added initially x

In [7]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

1. 100 --> France
2. 010 --> Germany
3. 001 --> Spain

3. Splitting into training and test set

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

4. FEATURE SCALING :- IT IS IMPORTANT FOR EVERY DL MODEL

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)   #no need of separating a particular feature
x_test=sc.transform(x_test)

BUILDING THE ANN

1. import the libraries, tf.keras.sequential must,tf.keras.layers.Dense are important

In [10]:
import tensorflow as tf
tf.__version__

'2.17.0'

2. initialise the ann

In [11]:
ann=tf.keras.Sequential()    #initialised the artificial neural network, its name is ann

3. add the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#first input layer is made then the first hidden layer is made with 6 neurons
#activation function is rectifier
#it is classfication therefore relu is used

4. add the second input hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  #6 neutrons

5. Add the last output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))  
#only one neuron needed as 0 for left, 1 for no left
#at the output layer the activation function is sigmoid as it is predicting something

COMPILING THE ARTIFICIAL NEURAL NETWORK

In [15]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
#optimiser adam means we are using stochastic gradient descent,remember to minimise the cost function
#if it is binary classification problem then do binary_crossentropy otherwise softmax
#it is classification problem therefore metrics is accuracy


TRAIN THE MODEL

In [16]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)
#batch size means at a time how many rows it is middle of batch learning and reinforcement learning
#epochs means no of round

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.6515 - loss: 0.6390
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7918 - loss: 0.4881
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7903 - loss: 0.4634 
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8052 - loss: 0.4345
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8173 - loss: 0.4184
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8230 - loss: 0.4230
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8284 - loss: 0.4089
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8330 - loss: 0.4061
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.8424 - loss: 0.3992
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.8508 - loss: 0.3771
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8456 - loss: 0.3834
Epoch 12/100
250/250 ━━━━━

Evaluate the model

In [17]:
y_pred = ann.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.03348816 0.        ]
 [0.01950834 0.        ]
 [0.14640218 0.        ]
 ...
 [0.78136009 1.        ]
 [0.12992328 1.        ]
 [0.29760391 1.        ]]


y_pred is in probability therfore convert it into binary

In [18]:
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


now evaluating the model

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print(f"The Accuracy of the ANN Model is {accuracy*100}")
print("Confusion Matrix\n")
print(cm)

The Accuracy of the ANN Model is 86.5
Confusion Matrix

[[1527   80]
 [ 190  203]]


Let's Evaluate a single prediction 

1. Use our ANN model to predict if the customer with the following informations will leave the bank: 
2. Geography: France
3. Credit Score: 600
4.Gender: Male
5. Age: 40 years old
6. Tenure: 3 years
7. Balance: $ 60000
8. Number of Products: 2
9. Does this customer have a credit card? Yes
10. Is this customer an Active Member: Yes
11. Estimated Salary: $ 50000
So, should we say goodbye to that customer?

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!
1. : Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.
2. : Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

pickle file

In [26]:
import pickle

# Save the trained ANN model
with open("churn_model.pkl", "wb") as f:
    pickle.dump(ann, f)

print("Model saved as churn_model.pkl")

Model saved as churn_model.pkl


In [27]:
# Assuming sc is already fitted on x_train
with open('scaler.pkl', 'wb') as f:
    pickle.dump(sc, f)

print("Scaler saved as scaler.pkl")


Scaler saved as scaler.pkl
